project:
  type: website

website:
  title: "cfpu-ds-da"
  description: "Course homepage for Data Science and Data Analytics at CFPU, Summer Semester 2025"
  
  sidebar:
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/jamon-R/cfpu-ds-da
        text: "GitHub repo to this website"

    style: docked
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - section: "Slides"
        contents:
          - href: getting-started.qmd
            text: Getting started
          - href: introduction-to-ds.qmd
            text: Introduction to data science
          - href: the-essentials-of-r-programming.qmd
            text: The essentials of R programming
          - href: the-ds-workflow-i.qmd
            text: The data science workflow I
          - href: the-ds-workflow-ii.qmd
            text: The data science workflow II
          - href: the-ds-workflow-iii.qmd
            text: The data science workflow III
          - href: the-ds-workflow-iv.qmd
            text: The data science workflow IV
      - href: image_sources.qmd
        text: Image Sources
            
  page-footer:
    right: 'This page is built with [Quarto](https://quarto.org/).'
    left: "&copy; Copyright 2025, Julian Amon, PhD"

format:
  html:
    theme:
      light: yeti
      dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto


